import nodemailer from "nodemailer";

import { EMAIL_VERIFICATION_CODE_LENGTH } from "../../config/constants";
import { logger } from "../logger";
import { describeActionUrl, maskEmailAddress } from "./redaction";

import type {
  AgentCredentialsEmailInput,
  EmailProvider,
  InvitationEmailInput,
  PasswordResetEmailInput,
  VerificationEmailInput,
} from "./emailProvider";
import type { Transporter } from "nodemailer";

/**
 * Sends mail through ANY SMTP server, including one you run yourself
 * (ADR-035 §7).
 *
 * The point of this provider is removing the vendor, not improving delivery.
 * `resendEmailProvider` talks to one company's HTTP API and cannot be pointed
 * anywhere else; this speaks the protocol every mail server speaks, so the
 * deployment decides where mail goes by setting `SMTP_HOST` — a self-hosted
 * Postfix, a corporate relay, a different vendor, or a local catcher during
 * development.
 *
 * **What it does not do is make mail arrive.** Whether Gmail accepts a message
 * is decided by the sending IP's reputation, by SPF/DKIM/DMARC alignment on the
 * sending domain, and by whether the sending network is one Gmail has reason to
 * trust — none of which is a property of the software that opened the socket.
 * A self-hosted server on a residential connection is the worst case for all
 * three, and moving from a vendor's warmed IP pool to one will make delivery
 * worse rather than better. This exists so that choice is available and
 * deliberate, not because it is the fix for mail landing in spam.
 *
 * The templates are duplicated from `resendEmailProvider` rather than shared,
 * and that is a deliberate cost: the two providers are the seam where a vendor
 * gets swapped, and a shared template module would be a third thing to keep in
 * step every time either changes. If a third provider arrives, extract then.
 */

export interface SmtpEmailProviderConfig {
  host: string;
  port: number;
  /** True for implicit TLS (port 465). False upgrades with STARTTLS where offered. */
  secure: boolean;
  /** Omitted for a relay that authenticates by IP, which a self-hosted one usually does. */
  user?: string;
  password?: string;
  /** The `From` header. Must be an address the receiving world will accept for this domain. */
  from: string;
}

interface EmailContent {
  subject: string;
  text: string;
  html: string;
}

/** Ten minutes, matching `EMAIL_VERIFICATION_TOKEN_TTL_MS`, stated for the reader. */
const VERIFICATION_EXPIRY_MINUTES = 10;

/**
 * Escapes the five characters that change meaning inside HTML.
 *
 * Every value interpolated into a template below is either generated by this
 * server or an organization name a person typed, and the second is enough
 * reason to escape all of them rather than reason about which are safe.
 */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function verificationEmail(code: string, url: string): EmailContent {
  return {
    subject: "Verify your email address",
    text:
      `Welcome to Serviqo.\n\n` +
      `Your ${EMAIL_VERIFICATION_CODE_LENGTH}-digit verification code is:\n\n` +
      `${code}\n\n` +
      `Enter it at ${url}\n\n` +
      `The code expires in ${VERIFICATION_EXPIRY_MINUTES} minutes.\n\n` +
      `If you didn't create a Serviqo account, you can ignore this email.`,
    html:
      `<p>Welcome to Serviqo.</p>` +
      `<p>Your ${EMAIL_VERIFICATION_CODE_LENGTH}-digit verification code is:</p>` +
      `<p style="font-size:28px;font-weight:700;letter-spacing:6px;font-family:ui-monospace,monospace">` +
      `${escapeHtml(code)}</p>` +
      `<p>Enter it at <a href="${escapeHtml(url)}">${escapeHtml(url)}</a></p>` +
      `<p>The code expires in ${VERIFICATION_EXPIRY_MINUTES} minutes.</p>` +
      `<p>If you didn't create a Serviqo account, you can ignore this email.</p>`,
  };
}

function passwordResetEmail(url: string): EmailContent {
  return {
    subject: "Reset your password",
    text: `We received a request to reset your Serviqo password.\n\nOpen this link to choose a new one:\n${url}\n\nIf you didn't request this, ignore this email.`,
    html:
      `<p>We received a request to reset your Serviqo password.</p>` +
      `<p><a href="${escapeHtml(url)}">Reset password</a></p>` +
      `<p>If you didn't request this, ignore this email.</p>`,
  };
}

function invitationEmail(organizationName: string, url: string): EmailContent {
  return {
    subject: `You've been invited to ${organizationName} on Serviqo`,
    text: `You've been invited to join ${organizationName} on Serviqo.\n\nAccept it here:\n${url}`,
    html:
      `<p>You've been invited to join <strong>${escapeHtml(organizationName)}</strong> on Serviqo.</p>` +
      `<p><a href="${escapeHtml(url)}">Accept invitation</a></p>`,
  };
}

function agentCredentialsEmail(
  organizationName: string,
  temporaryPassword: string,
  code: string,
  verificationUrl: string,
  signInUrl: string,
): EmailContent {
  return {
    subject: `You've been added to ${organizationName} on Serviqo`,
    text:
      `You've been added to ${organizationName} as a support agent.\n\n` +
      `Two steps, in this order.\n\n` +
      `1. Verify this address. Your ${EMAIL_VERIFICATION_CODE_LENGTH}-digit code is:\n\n` +
      `   ${code}\n\n` +
      `   Enter it at ${verificationUrl}\n` +
      `   The code expires in ${VERIFICATION_EXPIRY_MINUTES} minutes.\n\n` +
      `2. Sign in at ${signInUrl} with this temporary password:\n\n` +
      `   ${temporaryPassword}\n\n` +
      `Change it once you are in. This password is not stored anywhere and ` +
      `cannot be sent again — if you lose this email, ask your admin to add you again.`,
    html:
      `<p>You've been added to <strong>${escapeHtml(organizationName)}</strong> as a support agent.</p>` +
      `<p><strong>1. Verify this address.</strong> Your ${EMAIL_VERIFICATION_CODE_LENGTH}-digit code is:</p>` +
      `<p style="font-size:28px;font-weight:700;letter-spacing:6px;font-family:ui-monospace,monospace">` +
      `${escapeHtml(code)}</p>` +
      `<p>Enter it at <a href="${escapeHtml(verificationUrl)}">${escapeHtml(verificationUrl)}</a>. ` +
      `The code expires in ${VERIFICATION_EXPIRY_MINUTES} minutes.</p>` +
      `<p><strong>2. Sign in</strong> at <a href="${escapeHtml(signInUrl)}">${escapeHtml(signInUrl)}</a> ` +
      `with this temporary password:</p>` +
      `<p style="font-size:18px;font-weight:600;font-family:ui-monospace,monospace">` +
      `${escapeHtml(temporaryPassword)}</p>` +
      `<p>Change it once you are in. This password is not stored anywhere and cannot be sent again.</p>`,
  };
}

export function createSmtpEmailProvider(config: SmtpEmailProviderConfig): EmailProvider {
  /*
    One transporter for the process, reused across sends. Nodemailer pools
    connections behind it, so a burst of invitations does not open a TCP
    handshake and a TLS negotiation per message.
  */
  const transporter: Transporter = nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure,
    // Omitted entirely when absent, rather than sent as undefined: a relay that
    // authenticates by IP rejects an empty AUTH rather than ignoring it.
    ...(config.user !== undefined && config.password !== undefined
      ? { auth: { user: config.user, pass: config.password } }
      : {}),
  });

  /**
   * Sends one message and logs the attempt with SAFE FIELDS ONLY.
   *
   * The same rule `resendEmailProvider` follows, and it matters more here
   * because SMTP errors are chatty: a rejection can quote the message, and the
   * message contains a verification code or a password. Only the error's class
   * reaches the log, never its text.
   */
  async function deliver(event: string, to: string, actionUrl: string, content: EmailContent): Promise<void> {
    try {
      await transporter.sendMail({
        from: config.from,
        to,
        subject: content.subject,
        text: content.text,
        html: content.html,
      });

      logger.info(
        { event, delivery: "smtp", recipient: maskEmailAddress(to), url: describeActionUrl(actionUrl) },
        "Email sent over SMTP",
      );
    } catch (err: unknown) {
      logger.error(
        {
          event: `${event}.failed`,
          delivery: "smtp",
          recipient: maskEmailAddress(to),
          // The class, never the message — see above.
          failureType: err instanceof Error ? err.name : "UnknownError",
        },
        "SMTP delivery failed",
      );
      /*
        Rethrown as a plain Error. Callers decide what a failure means —
        registration treats it as non-fatal (ADR-008 §6), an agent invitation
        does not (ADR-034 §7) — and neither should have to read a transport
        error whose text can quote the message body.
      */
      // eslint-disable-next-line preserve-caught-error -- the original can quote the message
      throw new Error("SMTP delivery failed");
    }
  }

  return {
    async sendVerification(input: VerificationEmailInput): Promise<void> {
      await deliver(
        "email.smtp.verification",
        input.to,
        input.verificationUrl,
        verificationEmail(input.code, input.verificationUrl),
      );
    },

    async sendPasswordReset(input: PasswordResetEmailInput): Promise<void> {
      await deliver("email.smtp.password_reset", input.to, input.resetUrl, passwordResetEmail(input.resetUrl));
    },

    async sendInvitation(input: InvitationEmailInput): Promise<void> {
      await deliver(
        "email.smtp.invitation",
        input.to,
        input.invitationUrl,
        invitationEmail(input.organizationName, input.invitationUrl),
      );
    },

    async sendAgentCredentials(input: AgentCredentialsEmailInput): Promise<void> {
      await deliver(
        "email.smtp.agent_credentials",
        input.to,
        input.verificationUrl,
        agentCredentialsEmail(
          input.organizationName,
          input.temporaryPassword,
          input.code,
          input.verificationUrl,
          input.signInUrl,
        ),
      );
    },
  };
}
